fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.1.0
    apache:
      repo: git://github.com/puppetlabs/puppetlabs-apache.git
      ref: 1.0.1
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
      ref: 0.0.6
    concat: git://github.com/puppetlabs/puppetlabs-concat.git
  symlinks:
    awstats: "#{source_dir}"
